# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# Copyright (c) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
# NOTE: This file has been modified by Intel Corporation.

[project]
name = "torch-tweak-e5-large-v2-embedding-example"
dynamic = ["version"]
description = "Torch Tweak E5 Large V2 Embedding Example"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE", "third-party-programs.txt"]
requires-python = ">=3.10"

dependencies = [
    "torch-tweak[xpu]",
    "sentence_transformers>=6,<7",
]

[tool.uv]
index-strategy = "unsafe-best-match"

[tool.uv.sources]
torch_tweak = { path  = "../../" }
torch = { index = "pytorch-xpu" }
triton-xpu = { index = "pytorch-xpu" }
torchao = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-xpu"
url = "https://download.pytorch.org/whl/xpu"

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[project.scripts]
tune = "e5large.tune:main"
inference = "e5large.inference:main"

[build-system]
requires = ["setuptools>=83.0.0", "setuptools_scm[toml]>=10.2.0", "wheel>=0.47.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools_scm]
root = "../.."
local_scheme = "no-local-version"
fallback_version = "0.4.0"

[tool.setuptools.packages.find]
namespaces = false
include = ["e5large"]

[tool.setuptools.package-data]
e5large = ["**/*"]

[tool.ruff]
preview = true
line-length = 120
indent-width = 4
target-version = "py310"

[tool.ruff.lint]
select = ["B", "C", "C4", "C90", "D", "E", "F", "I", "N", "W", "T", "T10", "T20", "UP", "CPY"]
ignore = ["E266", "E501", "N818"]
exclude = []

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["D104"]
"**/__version__.py" = ["D100"]

[tool.ruff.lint.pydocstyle]
convention = "google"
